name: Build and Release

on:
  push:
    branches: [ nextgen ]
    tags:
      - 'v*'
  pull_request:
    branches: [ nextgen ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setting up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'

      - name: Grant permissions to src-theme
        run: sudo chmod -R 777 src-theme

      - name: Setup and build
        uses: gradle/gradle-build-action@v3
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: genSources build -x test -x detekt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BMWClient
          path: build/libs/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: BMWClient
          path: build/libs

      - name: Get tag name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/*.jar
          asset_name: BMWClient-${{ env.TAG_NAME }}.jar
          asset_content_type: application/java-archive